spring:
  application:
    name: SuperheroNameWeb

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
    eureka-connection-idle-timeout-seconds: 1
    registry-fetch-interval-seconds: 10

feign:
  hystrix:
    enabled: true
