CREATE TABLE IF NOT EXISTS PROPERTIES
(
  APPLICATION VARCHAR(256),
  PROFILE     VARCHAR(100),
  LABEL       VARCHAR(256),
  KEY         VARCHAR(256),
  VALUE       VARCHAR(256),
  PRIMARY KEY (APPLICATION, PROFILE, KEY)
);