apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fibonacci-simple-rc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fibonacci-numbers-simple-app
  template:
    metadata:
      labels:
        app: fibonacci-numbers-simple-app
    spec:
      containers:
        - name: fibonacci-numbers-simple-app
          image: afrunt/spring-cloud-examples-fibonacci-numbers-simple-app
          ports:
            - name: http
              containerPort: 9090
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              port: 9090
              path: /actuator/health
          livenessProbe:
            initialDelaySeconds: 30
            httpGet:
              port: 9090
              path: /actuator/health
          volumeMounts:
            - name: "config"
              mountPath: "/deployment/config/bootstrap.yml"
              subPath: "bootstrap.yml"
      volumes:
        - name: "config"
          configMap:
            name: "fibonacci-simple-cm"




