apiVersion: v1
kind: Service
metadata:
  name: fibonacci-simple-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      nodePort: 30123
  selector:
    app: fibonacci-numbers-simple-app