server:
  port: 8083

spring:
  application:
    name: LastInitialService

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka