server:
  port: 9090

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
    eureka-connection-idle-timeout-seconds: 1
    registry-fetch-interval-seconds: 10