server:
  port: 8081

spring:
  application:
    name: FirstInitialService

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka