server:
  port: 8082

spring:
  application:
    name: MiddleInitialService

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
    eureka-connection-idle-timeout-seconds: 1
    registry-fetch-interval-seconds: 10

hystrix:
  metrics:
    polling-interval-ms: 200
