server:
  port: 8082

spring:
  application:
    name: MiddleInitialService

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka

hystrix:
  metrics:
    polling-interval-ms: 200
